# This is a basic workflow to help you get started with Actions

name: deployment

# Controls when the workflow will run
on: 
  workflow_dispatch:
  push:
    tags:
      - v1.*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: test
      - run: echo "${{steps.wait-for-build.outputs.conclusion}}"
          # ref: ${{ github.event.pull_request.head.sha || github.sha }}
      # - uses: actions/github-script@v6
      #   with:
      #     script: |

      #         const query = await github.rest.checks.listForRef({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           ref: context.sha,
      #         });
      #         query.data.check_runs.every(check => check.conclusion === "success")
      #         console.log(JSON.stringify(checks))