# This is a basic workflow to help you get started with Actions

name: deployment

# Controls when the workflow will run
on: 
  workflow_dispatch:
  push:
    tags:
      - v1.*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{toJSON(github.event)}}"

      - uses: actions/github-script@v6
        with:
          script: |
              const checks = await github.rest.checks.listForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.sha,
              });

              console.log(JSON.stringify(checks))